/* Southern Grill — tum icerik burada. Admin paneli bunu localStorage'da gunceller. */
window.SG_DEFAULT = {
  meta: {
    name: "SOUTHERN GRILL",
    city: "MYRTLE BEACH, SC",
    headline1: "Gyros, burgers",
    headline2: "& cheesesteaks.",
    headline3: "Hot off the grill.",
    tagline: "Mediterranean plates, Southern comfort food and fresh salads — cooked to order, a few steps from the boardwalk.",
    place: "Broadway at the Beach",
    address1: "1118 Celebrity Circle #D315 · Floor 1",
    address2: "Myrtle Beach, SC 29577",
    phone: "(843) 251-5638",
    phoneRaw: "+18432515638",
    priceRange: "$10–20",
    mapsQuery: "Southern Grill, 1118 Celebrity Cir #D315, Myrtle Beach, SC 29577"
  },
  rating: { score: "4.7", count: "2,151", quote: "We saw all the usual spots and decided to give this one a try instead. INCREDIBLE!!!", quoteBy: "Google review" },
  announcement: { on: false, text: "Today's special: ask about the gyro platter 🥙" },
  hours: [
    { d: 0, day: "Sunday",    text: "11 AM – 10 PM", closed: false },
    { d: 1, day: "Monday",    text: "11 AM – 10 PM", closed: false },
    { d: 2, day: "Tuesday",   text: "11 AM – 10 PM", closed: false },
    { d: 3, day: "Wednesday", text: "11 AM – 10 PM", closed: false },
    { d: 4, day: "Thursday",  text: "11 AM – 10 PM", closed: false },
    { d: 5, day: "Friday",    text: "11 AM – 10 PM", closed: false },
    { d: 6, day: "Saturday",  text: "11 AM – 10 PM", closed: false }
  ],
  hoursSummary: "11 AM – 10 PM",
  order: [
    { on: true,  key: "clover",   label: "Order direct",  sub: "No extra fees",        url: "https://southern.cloveronline.com/menu/all" },
    { on: true,  key: "doordash", label: "DoorDash",      sub: "Delivery",             url: "https://www.doordash.com/store/southern-grill-myrtle-beach-615181/17011968/" },
    { on: true,  key: "grubhub",  label: "Grubhub",       sub: "Delivery",             url: "https://www.grubhub.com/restaurant/southern-grill-broadway-at-the-beach-1118-celebrity-cir-myrtle-beach/4828312" },
    { on: false, key: "ubereats", label: "Uber Eats",     sub: "Delivery",             url: "" }
  ],
  social: { facebook: "", instagram: "" },
  service: ["Dine in", "Takeout", "Curbside pickup", "Delivery"],
  loved: [
    { name: "The Gyro",          count: "120", rank: "#1 most mentioned", desc: "Seasoned meat, fresh vegetables and sauce in warm pita. The dish people come back to Broadway for." },
    { name: "Philly Cheesesteak",count: "96",  rank: "#2 most mentioned", desc: "Grilled steak, peppers, onions and melted cheese. Served with fries." },
    { name: "Wings",             count: "29",  rank: "#3 most mentioned", desc: "Crispy, sauced and shareable — the table order while you decide what else to get." }
  ],
  lovedNote: "Counts taken from public Google reviews. Also frequently named: chicken tenders (27), guacamole burger (20), onion rings (19), grilled chicken wrap (14), Greek salad (12).",
  categories: [
    { key: "all",           label: "Everything" },
    { key: "mediterranean", label: "Gyros & Wings" },
    { key: "burgers",       label: "Burgers" },
    { key: "sandwiches",    label: "Sandwiches" },
    { key: "wraps",         label: "Wraps & Tenders" },
    { key: "salads",        label: "Salads" },
    { key: "sides",         label: "Sides" },
    { key: "kids",          label: "Kids" },
    { key: "drinks",        label: "Drinks & Dessert" }
  ],
  menu: [
    { c:"mediterranean", n:"Gyro", p:"ask", d:"Seasoned meat, fresh veg and sauce in warm pita", badge:"#1 most reviewed" },
    { c:"mediterranean", n:"Wings", p:"ask", d:"Crispy and sauced — made for sharing", badge:"Guest favorite" },
    { c:"burgers", n:"Cheeseburger", p:"10.99", d:"The classic, cooked to order", badge:"" },
    { c:"burgers", n:"Ultimate Burger", p:"13.99", d:"Loaded and stacked", badge:"" },
    { c:"burgers", n:"Guacamole Burger", p:"13.99", d:"Fresh guac — the one people come back for", badge:"Favorite" },
    { c:"burgers", n:"Mushroom and Swiss", p:"12.99", d:"Sautéed mushrooms, melted swiss", badge:"" },
    { c:"burgers", n:"Very Veggie Burger", p:"13.99", d:"Full-size veggie patty", badge:"" },
    { c:"sandwiches", n:"Philly Steak and Cheese", p:"13.99", d:"Grilled steak, peppers, onions", badge:"#2 most reviewed" },
    { c:"sandwiches", n:"Chicken Cheesesteak w/ Fries", p:"13.99", d:"Comes with fries", badge:"" },
    { c:"sandwiches", n:"Grilled Chicken Sandwich", p:"12.99", d:"Marinated and grilled", badge:"" },
    { c:"sandwiches", n:"Crispy Chicken Sandwich", p:"12.99", d:"Hand-breaded, fried golden", badge:"" },
    { c:"sandwiches", n:"Buffalo Chicken Sub w/ Fries", p:"13.99", d:"Tossed in buffalo sauce", badge:"" },
    { c:"wraps", n:"Grilled Chicken Wrap w/ Fries", p:"12.99", d:"Comes with fries", badge:"" },
    { c:"wraps", n:"Crispy Chicken Wrap w/ Fries", p:"12.99", d:"Comes with fries", badge:"" },
    { c:"wraps", n:"Chicken Tenders (5 pcs)", p:"12.99", d:"Five hand-breaded tenders", badge:"" },
    { c:"salads", n:"Greek Salad", p:"15.99", d:"Feta, olives, fresh vegetables", badge:"" },
    { c:"salads", n:"Grilled Chicken Salad", p:"15.99", d:"Marinated chicken, lettuce, tomato, red onion, cucumber", badge:"" },
    { c:"salads", n:"Caesar Salad", p:"11.99", d:"Crisp romaine, parmesan", badge:"" },
    { c:"salads", n:"Ultimate Special Salad", p:"10.95", d:"House favorite", badge:"" },
    { c:"sides", n:"Large Fry", p:"7.99", d:"Golden and hot", badge:"" },
    { c:"sides", n:"Onion Rings", p:"8.99", d:"Thick cut, crispy", badge:"" },
    { c:"sides", n:"Mozzarella Sticks", p:"9.99", d:"With marinara", badge:"" },
    { c:"sides", n:"Fried Pickles", p:"10.99", d:"Southern staple", badge:"" },
    { c:"sides", n:"Mac & Cheese Bites", p:"10.99", d:"Crispy outside, creamy inside", badge:"" },
    { c:"sides", n:"Cheese on Fries", p:"2.99", d:"Add to any fries", badge:"" },
    { c:"sides", n:"Combo", p:"4.99", d:"Add fries and a drink", badge:"" },
    { c:"kids", n:"Kids Cheeseburger", p:"ask", d:"Served with fries", badge:"" },
    { c:"kids", n:"Kids Chicken Nuggets", p:"ask", d:"Served with fries", badge:"" },
    { c:"kids", n:"Kids Grilled Hot Dog", p:"ask", d:"Served with fries", badge:"" },
    { c:"kids", n:"Kids Grilled Cheese", p:"ask", d:"Served with fries", badge:"" },
    { c:"drinks", n:"Smoothie", p:"9.99", d:"Made fresh — guests mention these a lot", badge:"" },
    { c:"drinks", n:"Combo Fries & Smoothie", p:"12.99", d:"Fries plus a smoothie", badge:"" },
    { c:"drinks", n:"Hot Coffee", p:"ask", d:"Freshly brewed", badge:"" },
    { c:"drinks", n:"NY Style Cheesecake", p:"9.99", d:"Rich and creamy", badge:"" },
    { c:"drinks", n:"Bottled Beverage", p:"3.99", d:"Sodas and more", badge:"" },
    { c:"drinks", n:"Bottled Water", p:"3.99", d:"", badge:"" },
    { c:"drinks", n:"Cup of Water", p:"0.50", d:"", badge:"" }
  ],
  menuNote: "🍔 <b>Prices shown come from our online ordering menu.</b> Gyros, wings and the kids' menu are served in store — ask when you order. A 3% surcharge applies to credit card transactions.",
  reviews: [
    { stars: 5, text: "The guacamole burger was soooo good — I'll definitely be back to have it again before I leave my trip.", by: "Google review" },
    { stars: 5, text: "We took a day trip to the beach and were looking for a place that wasn't too crowded and had good food. We discovered Southern Grill and I'm so glad we did!", by: "Google review" },
    { stars: 5, text: "Summer vibe with hot chicken — they also have salad, Greek salad if you're vegetarian, and the real smoothies are fresh.", by: "Google review" }
  ],
  amenities: [
    { i:"i-kids",   t:"Great with kids",             x:"Kids' menu, high chairs and changing tables. Nuggets, grilled cheese, hot dogs and burgers — all with fries." },
    { i:"i-car",    t:"Free parking",                x:"Broadway at the Beach has free lots and a free garage. Curbside pickup if you'd rather stay in the car." },
    { i:"i-leaf",   t:"Vegetarian & halal options", x:"Veggie burger, Greek salad and more. Ask us — we'll point you to the right plate." },
    { i:"i-sun",    t:"Outdoor seating",             x:"Grab a table outside and watch Broadway go by, or take it to the lake." },
    { i:"i-dog",    t:"Dogs welcome",                x:"Your dog's allowed with you outside — plenty of walkers stop by between shops." },
    { i:"i-access", t:"Easy access",                 x:"Wheelchair accessible entrance, restrooms on site, counter service and table seating." },
    { i:"i-card",   t:"Pay how you like",            x:"Credit, debit and tap-to-pay accepted. Most guests spend $10–20 per person." },
    { i:"i-tray",   t:"Catering",                    x:"Feeding a group at the beach? Call us and we'll put a tray together." }
  ]
};
